# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # grabbed a docker image that had lftp from here -> https://github.com/AlpacaDB/docker-lftp
      - image: alpacadb/docker-lftp

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    # Environment variable for a single command shell
    environment:
      THEME_NAME: fullmoonrun

    steps:
      - checkout
      - run:
          name: debugging the shit out of it
          shell: /bin/sh
          command: |
            echo debuggin
            pwd
            ls -l
            lftp --version
            echo attempt 1 $SFTP_USERNAME
            echo attempt 2 ${SFTP_USERNAME}
            echo attempt 3 {{ .Environment.SFTP_USERNAME }}
            ftp $SFTP_USERNAME:$SFTP_PASSWORD@$SFTP_HOSTNAME
            ls -l
      - deploy:
          shell: /bin/sh
          command: |
            lftp sftp://$SFTP_USERNAME:$SFTP_PASSWORD@$SFTP_HOSTNAME -e '
            mirror -v -R ./wp-content/themes/fullmoonrun fullmoon/wp-content/themes/fullmoonrun
            quit
            '