# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # grabbed a docker image that had lftp from here -> https://github.com/AlpacaDB/docker-lftp
      - image: alpacadb/docker-lftp

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

      # sample lftp cmd below
      # lftp sftp://$SFTP_USERNAME:$SFTP_PASSWORD@$SFTP_HOSTNAME -e '
      # mirror -v -R ./wp-content/themes/fullmoonrun fullmoon/wp-content/themes/fullmoonrun
      # quit
      # '
      # lftp -c "open -u $SFTP_USERNAME,$SFTP_PASSWORD $SFTP_HOSTNAME;
      # put -O fullmoon/wp-content/themes/fullmoonrun ./wp-content/themes/fullmoonrun"
      #
      # lftp sftp://"$SFTP_USERNAME":"$SFTP_PASSWORD"@$SFTP_HOSTNAME

      # FTP cmds that work but dont recursively go through dirs
      # cd ./wp-content/themes/fullmoonrun/
      # ftp ftp://"$SFTP_USERNAME":"$SFTP_PASSWORD"@$SFTP_HOSTNAME
      # prompt
      # cd fullmoon/wp-content/themes/fullmoonrun
      # mput *

    working_directory: ~/repo

    # Environment variable for a single command shell
    environment:
      THEME_NAME: fullmoonrun

    steps:
      - checkout
      - run:
          name: debugging the shit out of it
          shell: /bin/sh
          command: |
            echo debuggin
            pwd
            ls -l
            lftp --version
            echo attempt 1 $SFTP_USERNAME
            echo attempt 2 ${SFTP_USERNAME}
            echo attempt 3 {{ .Environment.SFTP_USERNAME }}
      - deploy:
          shell: /bin/sh
          command: |
            lftp "$SFTP_USERNAME":"$SFTP_PASSWORD"@$SFTP_HOSTNAME -e 'set ftp:ssl-allow no
            mirror -v -R ./wp-content/themes/fullmoonrun fullmoon/wp-content/themes/fullmoonrun
            quit'