# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: alpacadb/docker-lftp

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    # Environment variable for a single command shell
    environment:
      THEME_NAME: fullmoonrun

    steps:
      - checkout
      - run:
          name: debugging the shit out of it
          shell: /bin/sh
          command: |
            echo debuggin
            pwd
            ls -l
            lftp --version
      - deploy:
          shell: /bin/sh
          command: |
            lftp sftp://${SFTP_USERNAME}:${SFTP_PASSWORD}@${SFTP_HOSTNAME} -e '
            mirror -v -R ./wp-content/themes/${THEME_NAME} ./wp-content/themes/${THEME_NAME}
            quit
            '